export const carsMock = [
  {
    id: 1,
    model: 'Fusca',
    brand: 'Volks',
    year: 1996,
    color: 'white',
    hasFine: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
  },
  {
    id: 2,
    model: 'Hb20',
    brand: 'Hyunday',
    year: 2018,
    color: 'black',
    hasFine: false,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
  },
  {
    id: 3,
    model: 'Dolphin',
    brand: 'BYD',
    year: 2024,
    color: 'grey',
    hasFine: false,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
  },
];
