import { RoleEnum } from '../../enums/role.enum';

export const usersMock = [
  {
    id: 1,
    firstName: 'Luiz Felipe',
    lastName: 'Dias',
    email: 'lf@gmail.com',
    password: '123456',
    role: RoleEnum.A,
    birthDate: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
  },
  {
    id: 2,
    firstName: 'Arnaldo',
    lastName: 'César',
    email: 'arnaldo@gmail.com',
    password: '123456',
    role: RoleEnum.I,
    birthDate: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
  },
  {
    id: 3,
    firstName: 'Mariah',
    lastName: 'Query',
    email: 'query@gmail.com',
    password: '123456',
    role: RoleEnum.I,
    birthDate: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
  },
  {
    id: 4,
    firstName: 'Jonas',
    lastName: 'Filipe',
    email: 'filipim@gmail.com',
    password: '123456',
    role: RoleEnum.S,
    birthDate: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
  },
];
